







function [] = chixyz(o)
picomax_cmd = sprintf( ...
    "-switch chixyz " + ...
    "-crystal %s -a %f -vg %s " + ...
    "-encut %d -neps %d " + ...
    "-nband %d " + ...
    "-nvalence %d " + ...
    "-nfreq %d -dfreq %f -kk %d -epsilon %f -delta %d ", ...
    o.sys.crystal,o.sys.a,regexprep(num2str(o.sys.vg),'\s+',','), ...
    o.num.encut,o.num.neps, ...
    o.num.nband,o.num.nvalence,...
    o.num.nfreq,o.num.dfreq,o.num.kk,o.num.epsilon,o.num.delta);

if ~isempty(o.sys.f) && (o.sys.f~=0)
    picomax_cmd = sprintf( ...
        "%s -f %f ", ...
        picomax_cmd,o.sys.f);
end

if ~isempty(o.sys.u) && (o.sys.u~=0)
    picomax_cmd = sprintf( ...
        "%s -u %f ", ...
        picomax_cmd,o.sys.u);
end

% 
picomax_cmd = sprintf( ...
    "%s -wdir %s " + ...
    "-outputfile %s ", ...
    picomax_cmd, ...
    [o.num.base_remote o.num.wdir], ...
    o.num.outputfile);



% BZ integration (KPOINT)
if o.num.kpoint==0
    picomax_cmd = sprintf( ...
        "%s -kpoint %d -kpointfile %s ", ...
        picomax_cmd, ...
        o.num.kpoint,o.num.kpointfile);
elseif o.num.kpoint==3 % Cohen-Chadi grid
    picomax_cmd = sprintf( ...
        "%s -kpoint %d -kpointorder %d ", ...
        picomax_cmd, ...
        o.num.kpoint,o.num.kpointorder);
elseif o.num.kpoint==2 % Monkhorst-Pack grid
    picomax_cmd = sprintf( ...
        "%s -kpoint %d -kpointorder %d ", ...
        picomax_cmd, ...
        o.num.kpoint,o.num.kpointorder);
elseif o.num.kpoint==1
    picomax_cmd = sprintf( ...
        "%s -kpoint %d -kpointorder %d ", ...
        picomax_cmd, ...
        o.num.kpoint,o.num.kpointorder);
end

% q vectors
if (~isempty(o.num.qnum) && ~isempty(o.num.qpath))
    picomax_cmd = ...
        sprintf("%s -qnum %s -qpath %s -refpoint %s", ...
        picomax_cmd, ...
        regexprep(num2str(o.num.qnum),'\s+',','), ...
        o.num.qpath, ...
        regexprep(num2str(o.num.refpoint(:).'),'\s+',','));
else
    picomax_cmd = ...
        sprintf("%s -qvec %s", ...
        picomax_cmd, ...
        regexprep(num2str(o.num.qvec(:).'),'\s+',','));
end


% construct system cmd
picomax_cmd = sprintf("%s %s", ...
    o.num.picomax_exe,picomax_cmd);
switch o.num.system
    case 'linux'
        system_cmd = picomax_cmd;
    case 'wsl'
        system_cmd = sprintf( ...
            "powershell -command ""wsl bash -c '%s'""", ...
            picomax_cmd);
end

% run the system cmd
tic
[status,cmdout] = system(system_cmd);
toc

% save the commands for debugging purposes
o.tmp.system_cmd = system_cmd;
o.tmp.picomax_cmd = picomax_cmd;
o.tmp.cmdout = cmdout;


% import the result file (.dat)
datfile = [o.num.base_local o.num.wdir o.num.outputfile '.dat'];
% fid = fopen(datfile,'r');
% eps = fread(fid,'double');
% fclose(fid);


o.import(datfile,'epsij');

datfile = [o.num.base_local o.num.wdir o.num.outputfile '_g.dat'];
o.import(datfile,'g');
end

