


function [] = electronband(o)
o.tmp.PICOMAX_OPT = sprintf( ...
    "-switch band -nband %d " + ...
    "-GCUT %f " + ...
    "-a %f -epm %s ", ...
    o.num.NBAND, ...
    o.num.GCUT, ...
    o.sys.a,regexprep(num2str(o.sys.epm),'\s+',','));

% q vectors
if (~isempty(o.num.QNUM) && ~isempty(o.num.QPATH))
    o.tmp.PICOMAX_OPT = ...
        sprintf("%s -numq %s -pathq %s", ...
        o.tmp.PICOMAX_OPT, ...
        regexprep(num2str(o.num.QNUM),'\s+',','), ...
        o.num.QPATH);
else
    o.tmp.PICOMAX_OPT = ...
        sprintf("%s -q %s", ...
        o.tmp.PICOMAX_OPT, ...
        regexprep(num2str(o.num.QVEC),'\s+',','));
end

o.tmp.SYSTEM_CMD = sprintf("powershell -command ""wsl bash -c '%s %s'""", ...
    o.num.PICOMAX_CMD,o.tmp.PICOMAX_OPT);

tic
[status,o.tmp.CMDOUT] = system(o.tmp.SYSTEM_CMD);
toc

tmp = splitlines(o.tmp.CMDOUT);
tmp(1:o.num.NumHeaderLines) = [];
tmp(end) = [];
o.dat.electronband = cell2mat(cellfun(@str2num,tmp,'uniform',0));
end