







function [] = permittivity(o)
o.tmp.PICOMAX_OPT = sprintf( ...
    "-switch eps " + ...
    "-encut %d -neps %d " + ...
    "-nband %d -originshift %d " + ...
    "-a %f -epm %s " + ...
    "-nfreq %d -dfreq %f -kk %d -epsilon %f -delta %d ", ...
    o.num.encut,o.num.neps, ...
    o.num.nband,o.num.originshift, ...
    o.sys.a,regexprep(num2str(o.sys.epm),'\s+',','), ...
    o.num.nfreq,o.num.dfreq,o.num.kk,o.num.epsilon,o.num.delta);


% 
o.tmp.PICOMAX_OPT = sprintf( ...
    "%s -wdir %s " + ...
    "-outputfile %s ", ...
    o.tmp.PICOMAX_OPT, ...
    [o.num.base_remote o.num.wdir], ...
    o.num.outputfile);



% BZ integration (KPOINT)
if o.num.kpoint==0
    o.tmp.PICOMAX_OPT = sprintf( ...
        "%s -kpoint %d -kpointfile %s ", ...
        o.tmp.PICOMAX_OPT, ...
        o.num.kpoint,o.num.kpointfile);
elseif o.num.kpoint==3 % Cohen-Chadi grid
    o.tmp.PICOMAX_OPT = sprintf( ...
        "%s -kpoint %d -kpointorder %d ", ...
        o.tmp.PICOMAX_OPT, ...
        o.num.kpoint,o.num.kpointorder);
elseif o.num.kpoint==2 % Monkhorst-Pack grid
    o.tmp.PICOMAX_OPT = sprintf( ...
        "%s -kpoint %d -kpointorder %d ", ...
        o.tmp.PICOMAX_OPT, ...
        o.num.kpoint,o.num.kpointorder);
end

% q vectors
if (~isempty(o.num.qnum) && ~isempty(o.num.qpath))
    o.tmp.PICOMAX_OPT = ...
        sprintf("%s -qnum %s -qpath %s", ...
        o.tmp.PICOMAX_OPT, ...
        regexprep(num2str(o.num.qnum),'\s+',','), ...
        o.num.qpath);
else
    o.tmp.PICOMAX_OPT = ...
        sprintf("%s -q %s", ...
        o.tmp.PICOMAX_OPT, ...
        regexprep(num2str(o.num.qvec(:).'),'\s+',','));
end

o.tmp.SYSTEM_CMD = sprintf( ...
    "powershell -command ""wsl bash -c '%s %s'""", ...
    o.num.picomax_exe,o.tmp.PICOMAX_OPT);

tic
[status,o.tmp.CMDOUT] = system(o.tmp.SYSTEM_CMD);
toc


% import the result file (.dat)
datfile = [o.num.base_local o.num.wdir o.num.outputfile '.dat'];
fid = fopen(datfile,'r');
eps = fread(fid,'double');
fclose(fid);


nfreq = o.num.nfreq;
o.dat.omega = o.num.dfreq*(0:1:nfreq-1);
if (~isempty(o.num.qnum) && ~isempty(o.num.qpath))
    nq = sum(o.num.qnum)+1;
    o.dat.qi = 0:nq-1;
else
    nq = 1;
    o.dat.qi = 0;
end
ne = o.num.neps*(o.num.neps+1)/2;
N = ne*nq*nfreq;


o.dat.realepsL = permute(reshape(eps(0*N+1:1*N),[nfreq ne nq]),[1 3 2]);
o.dat.imagepsL = permute(reshape(eps(1*N+1:2*N),[nfreq ne nq]),[1 3 2]);
o.dat.realepsT = permute(reshape(eps(2*N+1:3*N),[nfreq ne nq]),[1 3 2]);
o.dat.imagepsT = permute(reshape(eps(3*N+1:4*N),[nfreq ne nq]),[1 3 2]);
end

