% compute electron band structure directly in PicoMax (C++)

function [] = band_cpp(o)
picomax_cmd = sprintf( ...
    "-switch band -crystal %s -nband %d -nvalence %d " + ...
    "-encut %f " + ...
    "-a %f -vg %s ", ...
    o.sys.crystal, ...
    o.num.nband, o.num.nvalence, ...
    o.num.encut, ...
    o.sys.a,regexprep(num2str(o.sys.vg),'\s+',','));

if ~isempty(o.sys.f) && (o.sys.f~=0)
    picomax_cmd = sprintf( ...
        "%s -f %f ",picomax_cmd,o.sys.f);
end

if ~isempty(o.sys.u) && (o.sys.u~=0)
    picomax_cmd = sprintf( ...
        "%s -u %f ",picomax_cmd,o.sys.u);
end


% q vectors
if (~isempty(o.num.qnum) && ~isempty(o.num.qpath))
    picomax_cmd = ...
        sprintf("%s -qnum %s -qpath %s -refpoint %s", ...
        picomax_cmd, ...
        regexprep(num2str(o.num.qnum),'\s+',','), ...
        o.num.qpath, ...
        regexprep(num2str(o.num.refpoint(:).'),'\s+',','));
else
    picomax_cmd = ...
        sprintf("%s -q %s", ...
        picomax_cmd, ...
        regexprep(num2str(o.num.qvec),'\s+',','));
end

%
picomax_cmd = sprintf( ...
    "%s -wdir %s " + ...
    "-outputfile %s ", ...
    picomax_cmd, ...
    [o.num.base_remote o.num.wdir], ...
    o.num.outputfile);


% construct system cmd
picomax_cmd = sprintf("%s %s", ...
    o.num.picomax_exe,picomax_cmd);
switch o.num.system
    case 'linux'
        system_cmd = picomax_cmd;
    case 'wsl'
        system_cmd = sprintf( ...
            "powershell -command ""wsl bash -c '%s'""", ...
            picomax_cmd);
end

tic
[status,cmdout] = system(system_cmd);
toc

o.tmp.system_cmd = system_cmd;
o.tmp.picomax_cmd = picomax_cmd;
o.tmp.cmdout = cmdout;

% import the result file (.dat)
datfile = [o.num.base_local o.num.wdir o.num.outputfile '.dat'];


o.import(datfile,'eband');


% 
% tmp = splitlines(o.tmp.cmdout);
% tmp(1:o.num.NumHeaderLines) = [];
% tmp(end) = [];
% o.dat.electronband = cell2mat(cellfun(@str2num,tmp,'uniform',0));


end